#!/bin/bash
CARPETA=~/Escritorio/"${PWD##*/}_Cristo_García_González"
mkdir -p $CARPETA
cp -r * $CARPETA
make -C $CARPETA/build/ clean
tar -zcvf $CARPETA.tgz -C ~/Escritorio "${PWD##*/}_Cristo_García_González"
